config/routes.rb
Rails.application.routes.draw do
  resources :templates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :template_name %>
  </div>

  <div class="field">
    <%= form.label :structure %>
    <%= form.text_area :structure, id: :template_structure %>
  </div>

  <div class="field">
    <%= form.label :initial_prayer %>
    <%= form.text_area :initial_prayer, id: :template_initial_prayer %>
  </div>

  <div class="field">
    <%= form.label :motivation %>
    <%= form.text_area :motivation, id: :template_motivation %>
  </div>

  <div class="field">
    <%= form.label :gospel %>
    <%= form.text_area :gospel, id: :template_gospel %>
  </div>

  <div class="field">
    <%= form.label :activities %>
    <%= form.text_area :activities, id: :template_activities %>
  </div>

  <div class="field">
    <%= form.label :purpose %>
    <%= form.text_area :purpose, id: :template_purpose %>
  </div>

  <div class="field">
    <%= form.label :final_prayer %>
    <%= form.text_area :final_prayer, id: :template_final_prayer %>
  </div>

  <div class="field">
    <%= form.label :annexed %>
    <%= form.text_area :annexed, id: :template_annexed %>
  </div>

  <div class="field">
    <%= form.label :calendar %>
    <%= form.text_area :calendar, id: :template_calendar %>
  </div>

  <div class="field">
    <%= form.label :initial_year %>
    <%= form.number_field :initial_year, id: :template_initial_year %>
  </div>

  <div class="field">
    <%= form.label :initial_month %>
    <%= form.number_field :initial_month, id: :template_initial_month %>
  </div>

  <div class="field">
    <%= form.label :initial_day %>
    <%= form.number_field :initial_day, id: :template_initial_day %>
  </div>

  <div class="field">
    <%= form.label :final_year %>
    <%= form.number_field :final_year, id: :template_final_year %>
  </div>

  <div class="field">
    <%= form.label :final_month %>
    <%= form.number_field :final_month, id: :template_final_month %>
  </div>

  <div class="field">
    <%= form.label :final_day %>
    <%= form.number_field :final_day, id: :template_final_day %>
  </div>

  <div class="field">
    <%= form.label :monday_gospel %>
    <%= form.text_field :monday_gospel, id: :template_monday_gospel %>
  </div>

  <div class="field">
    <%= form.label :monday_saints %>
    <%= form.text_field :monday_saints, id: :template_monday_saints %>
  </div>

  <div class="field">
    <%= form.label :tuesday_gospel %>
    <%= form.text_field :tuesday_gospel, id: :template_tuesday_gospel %>
  </div>

  <div class="field">
    <%= form.label :tuesday_saints %>
    <%= form.text_field :tuesday_saints, id: :template_tuesday_saints %>
  </div>

  <div class="field">
    <%= form.label :wednesday_gospel %>
    <%= form.text_field :wednesday_gospel, id: :template_wednesday_gospel %>
  </div>

  <div class="field">
    <%= form.label :wednesday_saints %>
    <%= form.text_field :wednesday_saints, id: :template_wednesday_saints %>
  </div>

  <div class="field">
    <%= form.label :thursday_gospel %>
    <%= form.text_field :thursday_gospel, id: :template_thursday_gospel %>
  </div>

  <div class="field">
    <%= form.label :thursday_saints %>
    <%= form.text_field :thursday_saints, id: :template_thursday_saints %>
  </div>

  <div class="field">
    <%= form.label :friday_gospel %>
    <%= form.text_field :friday_gospel, id: :template_friday_gospel %>
  </div>

  <div class="field">
    <%= form.label :friday_saints %>
    <%= form.text_field :friday_saints, id: :template_friday_saints %>
  </div>

  <div class="field">
    <%= form.label :saturday_gospel %>
    <%= form.text_field :saturday_gospel, id: :template_saturday_gospel %>
  </div>

  <div class="field">
    <%= form.label :saturday_saints %>
    <%= form.text_field :saturday_saints, id: :template_saturday_saints %>
  </div>

  <div class="field">
    <%= form.label :sunday_gospel %>
    <%= form.text_field :sunday_gospel, id: :template_sunday_gospel %>
  </div>

  <div class="field">
    <%= form.label :sunday_saints %>
    <%= form.text_field :sunday_saints, id: :template_sunday_saints %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Templates</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descargar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><%=  %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Structure:</strong>
  <%= @template.structure %>
</p>

<p>
  <strong>Initial Prayer:</strong>
  <%= @template.initial_prayer %>
</p>

<p>
  <strong>Motivation:</strong>
  <%= @template.motivation %>
</p>

<p>
  <strong>Gospel:</strong>
  <%= @template.gospel %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @template.activities %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @template.purpose %>
</p>

<p>
  <strong>Final prayer:</strong>
  <%= @template.final_prayer %>
</p>

<p>
  <strong>Annexed:</strong>
  <%= @template.annexed %>
</p>

<p>
  <strong>Calendar:</strong>
  <%= @template.calendar %>
</p>

<p>
  <strong>Initial year:</strong>
  <%= @template.initial_year %>
</p>

<p>
  <strong>Initial month:</strong>
  <%= @template.initial_month %>
</p>

<p>
  <strong>Initial day:</strong>
  <%= @template.initial_day %>
</p>

<p>
  <strong>Final year:</strong>
  <%= @template.final_year %>
</p>

<p>
  <strong>Final month:</strong>
  <%= @template.final_month %>
</p>

<p>
  <strong>Final day:</strong>
  <%= @template.final_day %>
</p>

<p>
  <strong>Monday gospel:</strong>
  <%= @template.monday_gospel %>
</p>

<p>
  <strong>Monday saints:</strong>
  <%= @template.monday_saints %>
</p>

<p>
  <strong>Tuesday gospel:</strong>
  <%= @template.tuesday_gospel %>
</p>

<p>
  <strong>Tuesday saints:</strong>
  <%= @template.tuesday_saints %>
</p>

<p>
  <strong>Wednesday gospel:</strong>
  <%= @template.wednesday_gospel %>
</p>

<p>
  <strong>Wednesday saints:</strong>
  <%= @template.wednesday_saints %>
</p>

<p>
  <strong>Thursday gospel:</strong>
  <%= @template.thursday_gospel %>
</p>

<p>
  <strong>Thursday saints:</strong>
  <%= @template.thursday_saints %>
</p>

<p>
  <strong>Friday gospel:</strong>
  <%= @template.friday_gospel %>
</p>

<p>
  <strong>Friday saints:</strong>
  <%= @template.friday_saints %>
</p>

<p>
  <strong>Saturday gospel:</strong>
  <%= @template.saturday_gospel %>
</p>

<p>
  <strong>Saturday saints:</strong>
  <%= @template.saturday_saints %>
</p>

<p>
  <strong>Sunday gospel:</strong>
  <%= @template.sunday_gospel %>
</p>

<p>
  <strong>Sunday saints:</strong>
  <%= @template.sunday_saints %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>